### ISSUE TITLE
MultiFiltering page on demo site is broken

### ISSUE THREAD

**Issue by Korijn** [NonFactors/MVC.Grid#1]
Thanks for awesome work! Is this a fork of the original MVC.Grid?

The view 'MultiFiltering' or its master was not found or no view engine supports the searched locations. The following locations were searched:
~/Views/Grid/MultiFiltering.aspx
~/Views/Grid/MultiFiltering.ascx
~/Views/Shared/MultiFiltering.aspx
~/Views/Shared/MultiFiltering.ascx
~/Views/Grid/MultiFiltering.cshtml
~/Views/Grid/MultiFiltering.vbhtml
~/Views/Shared/MultiFiltering.cshtml
~/Views/Shared/MultiFiltering.vbhtml

http://mvc-grid.azurewebsites.net/Grid/MultiFiltering

**Comment by Muchiachio** [comment]
Thank you. No, it's not a fork it was created from zero, because I could not find a free and supported grid for MVC.
The website is fixed now, I was just looking at this error at that time.
