### ISSUE TITLE
Global search like Jquery Datatable plugin

### ISSUE THREAD

**Issue by ddmactive** [NonFactors/MVC.Grid#2]
It would be possible add this request?

Thanks for this amazing code

**Comment by Muchiachio** [comment]
It is possible to have that kind of functionality.
But here are the catches:
- Not all .NET data providers support number and date conversion to string using ```.ToString()```method in LINQ to Entities queries. And I don't particularly like the idea of having a functionality which is available for half the users and the other half just get's unsupported exceptions.
- We can't make sure that string's format being used by the database is the same as the one being used inside our C# code. So searching for numbers or dates in localized format, would result in unexpected filtering results, depending on thread and database cultures.

Knowing that I will not be implementing this functionality just yet, but I will definitely revisit it after the next cycle of EF/.NET data provider releases.

If you are still interested on how to extend current grid for global search functionality, which could work on things like MsSql + single locale configuration, etc. I could scribble a gist showing you how to do that.

**Comment by ddmactive** [comment]
Firstly thank you for your quick response.
My database engine is SQL Server and I would be very grateful if you could guide me to develop this functionality.

**Comment by Muchiachio** [comment]
[Here's](https://gist.github.com/Muchiachio/c897a96acbd8b3c1409d) a gist showing the idea behind global searching, you can find examples filter expression trees in the source code, under filtering folder. If you will have any questions feel free to ask them in the created gist.
