### ISSUE TITLE
Supporting a general search box

### ISSUE THREAD

**Issue by zjean** [NonFactors/MVC.Grid#3]
Hello,
I am looking for some kind of shortcut for the filtering the grid already supports by clicking the filter icon in a specific column.

I would like to implement a searchbox above the grid that searches all columns in the grid, or just the ones that have an attribute defined, just as the datalist does with the [DatalistColumn] attribute.
Can you guide me in the correct direction?

**Comment by Muchiachio** [comment]
This was already discussed in #2 issue not too long ago, you can find a [gist](https://gist.github.com/Muchiachio/c897a96acbd8b3c1409d) there, showing how to start implementing that kind of search. If you will have any other questions, you can always ask them in the [gist's](https://gist.github.com/Muchiachio/c897a96acbd8b3c1409d) comments.
