### ISSUE TITLE
How to create columns with anchors/buttons

### ISSUE THREAD

**Issue by rubensr** [NonFactors/MVC.Grid#7]
Hi, first of all thanks for this control, it is really well written and complete.

I've got a question - what is the best way to go about adding a column that for example contains "Edit" buttons for a row?

For example, if I'm writing a grid by hand, I can just write:@Html.ActionLink(model => model.Name, ,...)

What is the "proper" way of doing that with your control? Should I maybe create a subclass of GridColumn and override ValueFor(), or simply try to use the existing "RenderedAs()"?

Thanks!

**Comment by Muchiachio** [comment]
You can do a simple .Add(), you will just need to specify that it is not encoded content:
```C#
Html
    .Grid(Model)
    .Build(columns =>
    {
        columns.Add(model => "<a href='#'>Press me</a>").Encoded(false);
    })
```
Or you could write an extension method like .AddActionLink(), [here's](https://github.com/NonFactors/MVC.Template/blob/develop/src/MvcTemplate.Components/Extensions/Html/MvcGrid/MvcGridExtensions.cs#L22) a code example using extensions.
